### ISSUE TITLE
Config files with cyrillic letters get corrupted after converting to JSON.

### ISSUE THREAD

**Issue by kikugie** [Fallen-Breath/yamlang#1]
For example with a yaml line with every letter in Ukrainian alphabet:  
```yaml
alphabet: А а, Б б, В в, Г г, Ґ ґ, Д д, Е е, Є є, Ж ж, З з, И и, І і, Ї ї, Й й, К к, Л л, М м, Н н, О о, П п, Р р, С с, Т т, У у, Ф ф, Х х, Ц ц, Ч ч, Ш ш, Щ щ, ь, Ю ю, Я я
```
gets converted into:  
```json
{
  "alphabet": "�? а, Б б, В в, Г г, �? ґ, Д д, Е е, Є є, Ж ж, З з, И и, І і, Ї ї, Й й, К к, Л л, М м, �? н, О о, П п, Р р, С �?, Т т, У у, Ф ф, Х х, Ц ц, Ч ч, Ш ш, Щ щ, ь, Ю ю, Я �?"
}
```
Its not needed to understand every letter ofc, but some of them converting into "�?" is an issue that persists when being used in the game.

I have verified that encoding in the input file is UTF-8 and all letters are displayed correctly there. From what I've tested it appears it gets corrupted at the [point of reading the file](https://github.com/Fallen-Breath/yamlang/blob/cd26e21e498451e82a5c38c145bcceba14491335/src/main/java/me/fallenbreath/yamlang/Yamlang2JsonlangMapper.java#L19).

**Comment by Fallen-Breath** [comment]
Ah I forgot the chatset. Gonna make the charset to UTF-8 by default

**Comment by Fallen-Breath** [comment]
Try `60c6bdc361` and keep using utf8 encoding, see if it works now

i.e. 

```groovy
plugins {
    id 'me.fallenbreath.yamlang' version '60c6bdc361'
}
```

**Comment by kikugie** [comment]
Yep, it worked 👍
